---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: customer-api-versioned
  namespace: apps
  labels:
    area: customers
    module: crm
spec:
  pathPrefix: "/customers-versioned"
  currentVersion: customer-api-v2

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: customer-api-v1
  namespace: apps
spec:
  apiName: customer-api-versioned
  release: 1.0.0
  title: "Catch-all"
  service:
    name: customer-app
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml


---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: customer-api-v2
  namespace: apps
spec:
  apiName: customer-api-versioned
  release: 2.0.0
  title: "URI path"
  routes:
    - pathPrefix: /v2
  stripPathPrefix: true
  service:
    name: customer-app-v2
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml


---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: customer-api-v3
  namespace: apps
spec:
  apiName: customer-api-versioned
  release: 3.0.0
  title: "Query param"
  routes:
    - queryParams:
        v: "3"
  service:
    name: customer-app-v3
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml


---
apiVersion: hub.traefik.io/v1alpha1
kind: APIVersion
metadata:
  name: customer-api-v4
  namespace: apps
spec:
  apiName: customer-api-versioned
  release: 4.0.0
  title: "Header with multiple blocks & query params"
  routes:
    - headers:
        Version: "4"
    - queryParams:
        v: "4"
        lang: hu
    - pathPrefix: /v4
  stripPathPrefix: true
  service:
    name: customer-app-v4
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml

