---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: flight-api
  namespace: apps
  labels:
    area: flights
    module: erp
spec:
  pathPrefix: "/flights"
  service:
    openApiSpec:
      path: /openapi.yaml
      operationSets:
        - name: read-flights
          matchers:
            - methods:
                - GET
    name: flight-app
    port:
      number: 3000

---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: ticket-api
  namespace: apps
  labels:
    area: tickets
    module: crm
spec:
  pathPrefix: "/tickets"
  service:
    openApiSpec:
      path: /openapi.yaml
      operationSets:
        - name: cru-tickets
          matchers:
            - methods: ["GET","POST","PUT","PATCH"]
    name: ticket-app
    port:
      number: 3000
---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: custom-pick
spec:
  groups:
    - support
  apiSelector:
    matchExpressions:
      - key: area
        operator: In
        values:
          - flights
          - tickets
  operationFilter:
    include:
      - read-flights
      - cru-tickets