---
apiVersion: hub.traefik.io/v1alpha1
kind: APIRateLimit
metadata:
  name: apim-employees-drl
  namespace: apps
spec:
  apis:
  - name: employee-api
  groups:
  - admin
  limit: 5
  period: 30s
  strategy: distributed
  
---
apiVersion: hub.traefik.io/v1alpha1
kind: APIRateLimit
metadata:
  name: apim-fallback-drl
  namespace: apps
spec:
  apiSelector:
    matchExpressions:
      - key: area
        operator: In
        values:
          - flights
          - tickets
          - employee
  everyone: true
  limit: 2000
  period: 65s
  strategy: distributed
  