---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: flight-api
  namespace: apps
  labels:
    area: flights
    module: erp
spec:
  openApiSpec:
    path: /openapi.yaml
    operationSets:
      - name: read-flights
        matchers:
          - pathPrefix: "/flight"
            methods: ["GET"]

---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: ticket-api
  namespace: apps
  labels:
    area: tickets
    module: crm
spec:
  openApiSpec:
    path: /openapi.yaml
    operationSets:
      - name: cru-tickets
        matchers:
          - pathPrefix: "/ticket"
            methods: ["GET","POST","PUT","PATCH"]

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIAccess
metadata:
  name: support-access
  namespace: apps
spec:
  groups:
    - support
  apiSelector:
    matchExpressions:
      - key: area
        operator: In
        values:
          - flights
          - tickets
  operationFilter:
    include:
      - cru-tickets
      - read-flights