{
 "title": "Hub Dashboard",
 "tags": [ "hub" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "api_name", "label": "API Name", "query": { "query": "label_values(api_name)" } },
   {
    "name": "api_version_name",
    "label": "API Version",
    "query": {
     "query": "label_values({api_name=\"$api_name\"}, api_version_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total # of requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api_name, api_version_name) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "{{api_name}} {{api_version_name}}"
    }
   ]
  },
  {
   "title": "Total # of requests per API",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api_name) (increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[$__range])) > 0",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "Average error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\", code!~\"(2.+|401)\"}[$__range]))/sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\", code=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(traefik_hub_api_requests_duration_milliseconds_sum{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "All requests"
    },
    {
     "expr": "sum (rate(traefik_hub_api_requests_duration_milliseconds_sum{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\", code!~\"(2.*|401)\"}[1m])) > 0",
     "legendFormat": "Non 2xx Requests"
    }
   ]
  },
  {
   "title": "Requests per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (api_name, api_version_name) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "{{api_name}} {{api_version_name}}"
    }
   ]
  },
  {
   "title": "Latency per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (api_name, api_version_name) (rate(traefik_hub_api_requests_duration_milliseconds_sum{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "{{api_name}} {{api_version_name}}"
    }
   ]
  },
  {
   "title": "Error rate per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (api_name, api_version_name) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\", code!~\"(2.*|401)\"}[1m]))/sum by (api_name) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m]))",
     "legendFormat": "{{api_name}} {{api_version_name}}"
    }
   ]
  }
 ]
}