    deployment:
      replicas: 1
    
    certResolvers:
      le:
        email: maytham.alfouadi@traefik.io
        tlsChallenge: true
        storage: /data/acme.json
    ingressClass:
      enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
        allowEmptyServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowEmptyServices: true
    logs:
      general:
        format: json
        level: DEBUG
      access:
        enabled: true
        format: json
        addInternals: true
        fields:
          general:
            defaultmode: keep
          headers:
            defaultmode: keep
    service:
      type: LoadBalancer