---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oidc-whoami
  namespace: apps
spec:
  plugin:
    oidc:
      issuer: "https://sts.windows.net/<tenant-id>/"
      clientID: "<client-id>"
      clientSecret: "<client-secret>"
      redirectUrl: "/cback"
      
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: whoami-ingress
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`whoami.traefik.${EXTERNAL_IP}.sslip.io`)
      services:
        - name: whoami
          port: 80
      middlewares:
        - name: oidc-whoami
  tls:
    certResolver: le