{
 "title": "API Management",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "# API management resources",
   "type": "barchart",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "traefik_hub_api_nodes_ratio", "legendFormat": "nodes" },
    { "expr": "traefik_hub_acps_ratio", "legendFormat": "acps" },
    {
     "expr": "traefik_hub_api_collections_ratio",
     "legendFormat": "api collections"
    },
    {
     "expr": "traefik_hub_api_rate_limits_ratio",
     "legendFormat": "api rate limits"
    },
    { "expr": "traefik_hub_api_accesses_ratio", "legendFormat": "api accesses" },
    { "expr": "traefik_hub_api_gateways_ratio", "legendFormat": "gateways" },
    {
     "expr": "traefik_hub_portals_ratio{portal_type=\"single_cluster\"}",
     "legendFormat": "portals"
    },
    {
     "expr": "traefik_hub_api_gateway_apis_ratio{}",
     "legendFormat": "apis"
    },
    {
     "expr": "traefik_hub_api_versions_ratio{}",
     "legendFormat": "api versions"
    },
    {
     "expr": "sum(traefik_hub_api_keys_ratio{})",
     "legendFormat": "api keys"
    }
   ]
  }
 ]
}
{
 "title": "API",
 "tags": [ "hub" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "api_name", "label": "API Name", "query": { "query": "label_values(api_name)" } },
   {
    "name": "api_version_name",
    "label": "API Version Name",
    "query": {
     "query": "label_values({api_name=\"$api_name\"}, api_version_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total # of requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\",api_version_name=~\"$api_version_name\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(email) (traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\",code!=\"401\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (email) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\",code!=\"401\"}[1m])) > 0",
     "legendFormat": "{{email}}"
    }
   ]
  },
  {
   "title": "Per method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", code!~\"(2.+)\", api_version_name=~\"$api_version_name\"}[$__range]))/sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_hub_api_requests_total{api_name=~\"$api_name\",api_version_name=~\"$api_version_name\"}[1m])) by (api_name, api_version_name)",
     "legendFormat": "All requests on {{api_name}} {{api_version_name}}"
    },
    {
     "expr": "sum(rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\", code!~\"2.*\"}[1m]))  by (api_name, api_version_name)",
     "legendFormat": "Non 2xx Requests on {{api_name}} {{api_version_name}}"
    }
   ]
  },
  {
   "title": "Latency per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (api_name, api_version_name) (rate(traefik_hub_api_requests_duration_milliseconds_sum{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "{{api_name}} {{api_version_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Hub Dashboard",
 "tags": [ "hub" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "api_name", "label": "API Name", "query": { "query": "label_values(api_name)" } },
   {
    "name": "api_version_name",
    "label": "API Version",
    "query": {
     "query": "label_values({api_name=\"$api_name\"}, api_version_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total # of requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api_name, api_version_name) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "{{api_name}} {{api_version_name}}"
    }
   ]
  },
  {
   "title": "Total # of requests per API",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api_name) (increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[$__range])) > 0",
     "legendFormat": "{{api_name}}"
    }
   ]
  },
  {
   "title": "Average error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\", code!~\"(2.+|401)\"}[$__range]))/sum(increase(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\", code=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (code) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(traefik_hub_api_requests_duration_milliseconds_sum{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "All requests"
    },
    {
     "expr": "sum (rate(traefik_hub_api_requests_duration_milliseconds_sum{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\", code!~\"(2.*|401)\"}[1m])) > 0",
     "legendFormat": "Non 2xx Requests"
    }
   ]
  },
  {
   "title": "Requests per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (api_name, api_version_name) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "{{api_name}} {{api_version_name}}"
    }
   ]
  },
  {
   "title": "Latency per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (api_name, api_version_name) (rate(traefik_hub_api_requests_duration_milliseconds_sum{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m])) > 0",
     "legendFormat": "{{api_name}} {{api_version_name}}"
    }
   ]
  },
  {
   "title": "Error rate per API",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (api_name, api_version_name) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\", code!~\"(2.*|401)\"}[1m]))/sum by (api_name) (rate(traefik_hub_api_requests_total{api_name=~\"$api_name\", api_version_name=~\"$api_version_name\"}[1m]))",
     "legendFormat": "{{api_name}} {{api_version_name}}"
    }
   ]
  }
 ]
}
{
 "title": "Users",
 "tags": [ "hub" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "email", "label": "Email", "query": { "query": "label_values(email)" } },
   {
    "name": "token_name",
    "label": "Token Name",
    "query": {
     "query": "label_values(traefik_hub_api_requests_duration_milliseconds_bucket{email=~\"$email\"},token_name)"
    }
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Tokens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "traefik_hub_api_keys_ratio{user_email=\"$email\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total # of requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\", code=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# APIs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (api_name) (traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\"}))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average error rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(increase(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\", code!~\"2.+\"}[$__range]))/sum(increase(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\", code=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API requests per token and code",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 20, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (code, api_name, method, token_name) (rate(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\",code=~\".+\"}[1m])) > 0",
     "legendFormat": "[{{code}}] {{api_name}} {{method}} {{token_name}}"
    }
   ]
  },
  {
   "title": "Per Token",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (token_name) (rate(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\",code=~\".+\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per API",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (api_name) (rate(traefik_hub_api_requests_total{email=~\"$email\", token_name=~\"$token_name\",code=~\".+\"}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}