---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: customer-api
  namespace: apps
  labels:
    area: customer
    module: crm
spec:
  openApiSpec:
    path: /openapi.yaml

---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: admins
  namespace: apps
spec:
  title: "Admins Plan"
  description: "Admins rate limits and quotas"
  rateLimit:
    limit: 5
    period: 10s
  quota:
    limit: 1000
    period: 720h # Approximately 30 days

---
apiVersion: hub.traefik.io/v1alpha1
kind: APICatalogItem
metadata:
  name: customer-api
  namespace: apps
spec:
  everyone: true
  apis:
    - name: customer-api
    - name: employee-api
    - name: flights-api
  apiPlan:
    name: admins

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingress-customers
  namespace: apps
  annotations:                                      # Add API annotation to enable APIM
    hub.traefik.io/api: customer-api
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`api.traefik.${EXTERNAL_IP}.sslip.io`) && PathPrefix(`/customers`)
      services:
        - name: customer-app
          port: 3000
  tls:
    certResolver: le
