 $clear
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-app-admin
  namespace: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-app-admin
  template:
    metadata:
      labels:
        app: traffic-app-admin
    spec:
      containers:
        - name: traffic
          image: mmatur/tools:latest
          args:
            - /data/traffic.sh
          env:
            - name: GW_DOMAIN
              value: api.traefik.${EXTERNAL_IP}.sslip.io
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokens
                  key: admin
          imagePullPolicy: Always
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
        - name: data
          configMap:
            name: traffic-data
            defaultMode: 0777

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-app-support
  namespace: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-app-support
  template:
    metadata:
      labels:
        app: traffic-app-support
    spec:
      containers:
        - name: traffic
          image: mmatur/tools:latest
          args:
            - /data/traffic.sh
          env:
            - name: GW_DOMAIN
              value: api.traefik.${EXTERNAL_IP}.sslip.io
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokens
                  key: support
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          configMap:
            name: traffic-data
            defaultMode: 0777
